#include <iostream>
#include <vector>
#include "Sentences.h"
using namespace std;

vector<string> spaceSentences = {
        "The universe is vast and mysterious.",
        "The Milky Way is our home galaxy.",
        "Astronomers study distant stars and galaxies.",
        "Space exploration has led to many discoveries.",
        "The International Space Station orbits Earth.",
        "The moon has a barren, rocky surface.",
        "Mars is often called the Red Planet.",
        "The sun is a giant ball of hot gas.",
        "Black holes have extremely strong gravity.",
        "Comets have icy tails.",
        "The Hubble Space Telescope captures stunning images.",
        "Satellites orbit our planet.",
        "The Big Bang is the origin of the universe.",
        "Astronauts experience weightlessness in space.",
        "Telescopes help us see distant objects.",
        "Space travel has challenges like radiation.",
        "The Mars rover explores the Red Planet.",
        "Solar flares can affect Earth's technology.",
        "Space agencies plan missions to other planets.",
        "The Great Red Spot is a famous feature on Jupiter.",
        "Saturn's rings are made of ice and rock.",
        "Space is a vacuum with no air.",
        "Asteroids can impact Earth.",
        "The Andromeda Galaxy is on a collision course with the Milky Way.",
        "Nebulas are regions of gas and dust in space.",
        "Exoplanets are planets outside our solar system.",
        "Space telescopes like Kepler search for exoplanets.",
        "The Oort Cloud is a vast region of comets.",
        "Astronomers observe stars to learn about their life cycles.",
        "The James Webb Space Telescope will be launched soon.",
        "Pluto is now classified as a dwarf planet.",
        "Space debris poses a threat to satellites.",
        "The speed of light is approximately 299,792 kilometers per second.",
        "Astronomers use spectrometry to analyze starlight.",
        "The moon's gravity affects Earth's tides.",
        "A spacewalk is a risky but essential part of space missions.",
        "The Great Attractor is a mysterious cosmic force.",
        "Galaxies can collide and merge over cosmic time.",
        "Space travel requires advanced technology and rigorous training.",
        "The Crab Nebula is a remnant of a supernova explosion.",
        "The Voyager probes are the farthest human-made objects from Earth.",
        "The sun's core is a fusion reactor.",
        "The outer planets are gas giants.",
        "Space tourism may become more common in the future.",
        "Cosmic rays are high-energy particles from space.",
        "The Great Wall of China is visible from space.",
        "The theory of relativity was formulated by Albert Einstein.",
        "Dark matter and dark energy are mysteries in cosmology.",
        "Meteor showers occur when Earth passes through comet debris.",
        "The search for extraterrestrial life continues in the universe."
    };

    vector<string> natureSentences = {
        "The beauty of nature is awe-inspiring.",
        "Forests are essential for maintaining ecological balance.",
        "Wildlife conservation is vital for biodiversity.",
        "Hiking in the mountains provides a sense of adventure.",
        "Sunsets over the ocean create stunning vistas.",
        "Rivers and lakes are habitats for various aquatic species.",
        "The sound of birds singing in the morning is soothing.",
        "Camping allows people to reconnect with nature.",
        "National parks preserve natural wonders for future generations.",
        "Deserts are harsh environments with unique adaptations.",
        "Fresh air in the countryside is refreshing and invigorating.",
        "Rainforests are the lungs of our planet.",
        "Butterflies are delicate and beautiful creatures.",
        "Watching a waterfall can be a meditative experience.",
        "Gardening is a relaxing and rewarding hobby.",
        "The smell of pine trees in the forest is invigorating.",
        "Ocean waves have a calming effect on the mind.",
        "Flowers come in a multitude of colors and shapes.",
        "Hiking through a meadow feels like stepping into a painting.",
        "Whales are majestic giants of the sea.",
        "Nature provides countless opportunities for photography.",
        "Starry nights in the wilderness are mesmerizing.",
        "Wildflowers add vibrant colors to the landscape.",
        "Coral reefs are teeming with marine life.",
        "Exploring caves reveals hidden underground worlds.",
        "The harmony of nature is a source of inspiration for artists.",
        "Geological formations tell stories of Earth's history.",
        "Observing wildlife in its natural habitat is a privilege.",
        "Diverse ecosystems support a variety of species.",
        "Birdwatching reveals the diversity of avian life.",
        "Mountains challenge and inspire climbers.",
        "Rainbows are natural phenomena that bring joy.",
        "The scent of a pine forest is invigorating.",
        "Lakeshores are peaceful places for reflection.",
        "Countryside landscapes are filled with picturesque views.",
        "A gentle breeze rustling leaves is a serene sound.",
        "Wetlands are essential for water purification.",
        "Cacti are resilient plants in arid regions.",
        "Lunar eclipses are astronomical marvels.",
        "Bee pollination is crucial for agriculture.",
        "Volcanoes shape the Earth's surface.",
        "Swimming in the ocean is a liberating experience.",
        "Autumn leaves create a colorful carpet on the ground.",
        "Waterfalls provide a sense of wonder and power.",
        "The ocean is a vast, unexplored realm.",
        "Sunrises symbolize new beginnings.",
        "Fields of lavender are visually and aromatically pleasing.",
        "Babbling brooks offer soothing background sounds.",
        "Bamboo forests are tranquil places for meditation."
    };

    vector<string> techSentences = {
        "Technology is rapidly advancing.",
        "Smartphones have become an essential part of our lives.",
        "Artificial intelligence is transforming various industries.",
        "The Internet of Things (IoT) connects everyday objects to the internet.",
        "Cybersecurity is crucial in the digital age.",
        "Virtual reality offers immersive experiences.",
        "Blockchain technology is changing how we handle transactions.",
        "Machine learning is used for data analysis and predictions.",
        "Renewable energy sources like solar power are eco-friendly.",
        "Drones are used for various applications, from photography to delivery.",
        "The world is becoming increasingly interconnected through technology.",
        "3D printing allows for rapid prototyping and manufacturing.",
        "Self-driving cars are a glimpse into the future of transportation.",
        "Quantum computing has the potential to revolutionize computing power.",
        "Social media platforms have transformed communication and networking.",
        "Video conferencing has become essential for remote work and communication.",
        "E-commerce is changing the way we shop and do business.",
        "Robots are used in manufacturing, healthcare, and more.",
        "Augmented reality enhances real-world experiences.",
        "Cloud computing provides scalable and cost-effective solutions.",
        "Biotechnology innovations are improving healthcare and medicine.",
        "Wireless technology has untethered us from cables and wires.",
        "Data analytics helps businesses make informed decisions.",
        "Digital assistants like Siri and Alexa are becoming common.",
        "Smart homes are equipped with automation and control systems.",
        "E-waste recycling is important for environmental sustainability.",
        "The open-source movement promotes collaboration and innovation.",
        "Tech startups drive innovation and disrupt traditional industries.",
        "Cryptocurrency is changing the way we think about money and finance.",
        "Wearable technology includes smartwatches and fitness trackers.",
        "Mobile apps offer convenience and utility for users.",
        "The sharing economy encourages resource-sharing and sustainability.",
        "Big data analysis is used in healthcare for research and diagnoses.",
        "Voice recognition technology powers speech-to-text and virtual assistants.",
        "Biometric security measures include fingerprint and facial recognition.",
        "The gig economy provides flexible work opportunities.",
        "Holographic displays offer unique visual experiences.",
        "E-sports have gained popularity as competitive video gaming.",
        "Autonomous drones can perform tasks without human intervention.",
        "Wireless charging eliminates the need for cords and plugs.",
        "Self-learning algorithms adapt and improve over time.",
        "Tech education equips students with digital skills for the future.",
        "Quantum cryptography ensures secure communication channels.",
        "Renewable energy technologies are reducing our carbon footprint.",
        "Neural networks mimic human brain function for machine learning.",
        "Remote learning and telemedicine have expanded access to education and healthcare.",
        "E-scooters and electric bikes provide eco-friendly transportation options.",
        "Genetic engineering is advancing agriculture and medicine.",
        "Biometric payment methods offer secure and convenient transactions.",
    };

    vector<string> foodSentences = {
        "Fresh vegetables are a key component of a healthy diet.",
        "Chocolate is a popular treat enjoyed by many.",
        "Spices and herbs can add flavor and depth to your dishes.",
        "Homemade meals often taste better than fast food.",
        "A balanced diet includes a variety of food groups.",
        "Apples are a nutritious and delicious snack.",
        "Mediterranean cuisine is known for its use of olive oil and fresh ingredients.",
        "Sushi is a Japanese dish that includes raw fish and rice.",
        "Baking bread from scratch can be a rewarding experience.",
        "Barbecue is a beloved American cuisine with regional variations.",
        "Italian pasta comes in a wide range of shapes and sizes.",
        "Gourmet dining is known for its artistic presentation of dishes.",
        "Healthy eating is important for maintaining overall well-being.",
        "French cuisine is celebrated for its culinary techniques and flavors.",
        "Food trucks offer a diverse array of street food options.",
        "Plant-based diets are becoming increasingly popular.",
        "Culinary school can help you develop your cooking skills.",
        "Cultural diversity is reflected in the world's cuisines.",
        "Desserts are a sweet way to end a meal on a high note.",
        "Cooking with fresh, locally sourced ingredients is a growing trend.",
        "Food allergies can impact dietary choices and meal planning.",
        "Farm-to-table restaurants emphasize locally grown produce.",
        "The Mediterranean diet is associated with longevity and health.",
        "Crispy fried chicken is a classic comfort food.",
        "Food preservation techniques include canning and pickling.",
        "Food festivals showcase a wide range of culinary delights.",
        "Smoothies are a popular choice for a quick and healthy breakfast.",
        "Taste is influenced by a combination of flavors and aromas.",
        "Family recipes are often cherished and passed down through generations.",
        "Savoring a meal in good company is a joyful experience.",
        "Seasonal ingredients are highlighted in many cuisines.",
        "Gourmet coffee shops offer unique and artisanal brews.",
        "Farmers' markets feature fresh produce and homemade goods.",
        "Pairing wine with the right dish enhances the dining experience.",
        "Gardening can be a source of fresh herbs and vegetables for your kitchen.",
        "Street food vendors offer a glimpse into local culinary traditions.",
        "Spicy dishes can be both flavorful and exhilarating.",
        "Exploring world cuisines can be a delicious adventure.",
        "Eating in moderation is a key principle of a healthy diet.",
        "Regional specialties are a highlight of travel experiences.",
        "Cookbooks provide a wealth of recipes and culinary inspiration.",
        "Breakfast is often considered the most important meal of the day.",
        "Picnics are a delightful way to enjoy a meal in nature.",
        "Food sustainability is a growing concern for our planet.",
        "Homemade soups are both comforting and nourishing.",
        "Learning to cook can be a valuable life skill.",
        "Farm animals provide a variety of meat and dairy products.",
        "Dining etiquette varies among cultures and social settings."
    };

    vector<string> sportsSentences = {
        "Basketball is a fast-paced team sport.",
        "Soccer is the world's most popular sport.",
        "Baseball is known as America's pastime.",
        "The Olympic Games bring athletes from all over the world.",
        "Tennis is a popular racket sport.",
        "Swimming is a great way to stay in shape.",
        "Golf requires precision and patience.",
        "Football is a contact sport loved by many.",
        "Running marathons is a test of endurance.",
        "Volleyball is played on a rectangular court.",
        "Hockey is played with a puck and sticks.",
        "Cycling is a great outdoor activity.",
        "Gymnastics showcases incredible flexibility and strength.",
        "Boxing is a combat sport with weight classes.",
        "Surfing is a popular water sport.",
        "Martial arts include disciplines like karate and judo.",
        "Cheerleading involves spirited routines and stunts.",
        "Rugby is a tough and physical sport.",
        "Equestrian sports involve horses and riders.",
        "Wrestling is a grappling combat sport.",
        "Table tennis is a fast-paced indoor game.",
        "Archery requires precise aim and focus.",
        "Badminton is a fun racquet sport.",
        "Track and field events include running and jumping.",
        "Snowboarding is a popular winter sport.",
        "Skateboarding is a cool street sport.",
        "Climbing mountains is a challenging adventure.",
        "Sailing takes place on open waters.",
        "Bowling is a popular indoor game.",
        "Bungee jumping is an extreme sport.",
        "Parkour involves agile movements in urban environments.",
        "Weightlifting tests strength and technique.",
        "Ice skating is a graceful and elegant sport.",
        "Fencing is a traditional combat sport.",
        "Ultimate Frisbee is a high-paced team game.",
        "Paddleboarding is a relaxing water sport.",
        "Curling is a strategic winter sport.",
        "Racquetball is played in a small court.",
        "Triathlons combine swimming, biking, and running.",
        "Extreme sports like skydiving provide thrills.",
        "Roller derby is a fast and physical roller skating sport.",
        "High jump is an exciting track and field event.",
        "Mountain biking is an adventurous outdoor activity.",
        "Powerlifting is all about lifting heavy weights.",
        "Synchronized swimming is an elegant water sport.",
        "Paragliding offers a unique flying experience.",
        "Ski jumping is a daring winter sport.",
        "Kite surfing is a wind-powered water sport."
    };

    vector<string> healthSentences = {
        "Regular exercise is important for maintaining good health.",
        "A balanced diet contributes to overall well-being.",
        "Getting enough sleep is essential for a healthy lifestyle.",
        "Proper hydration is vital for bodily functions.",
        "Mental health is as important as physical health.",
        "Regular check-ups with a healthcare provider are recommended.",
        "Avoiding smoking and excessive alcohol consumption promotes health.",
        "Stress management is crucial for a healthy mind and body.",
        "A positive outlook on life can improve your health.",
        "Maintaining a healthy weight reduces the risk of chronic diseases.",
        "Preventive care includes vaccinations and screenings.",
        "Physical activity helps strengthen the immune system.",
        "Eating fruits and vegetables provides essential nutrients.",
        "Adequate rest promotes muscle recovery and tissue repair.",
        "Proper dental care contributes to overall health.",
        "Regular handwashing helps prevent the spread of diseases.",
        "Healthy relationships have a positive impact on well-being.",
        "Avoiding processed foods can improve your health.",
        "Sunscreen helps protect the skin from harmful UV rays.",
        "Vitamin D is important for bone health.",
        "A well-functioning digestive system is key to good health.",
        "Good posture is essential for spinal health.",
        "Regular relaxation and meditation promote mental clarity.",
        "Preventing injuries is essential for long-term health.",
        "Physical therapy can aid in recovery from injuries.",
        "Adequate protein intake supports muscle health.",
        "Reducing sugar intake is beneficial for overall health.",
        "Maintaining a healthy heart is crucial for longevity.",
        "Hygiene practices prevent illness and infection.",
        "Regular cardiovascular exercise benefits the heart.",
        "Balancing work and personal life is important for mental health.",
        "Avoiding substance abuse is a key aspect of health.",
        "Getting fresh air and outdoor time promotes well-being.",
        "Proper footwear is important for foot and joint health.",
        "Early detection of health issues can lead to better outcomes.",
        "Mindful eating encourages healthy food choices.",
        "Adequate fiber intake supports digestive health.",
        "Regular eye exams are important for vision health.",
        "Proper ergonomics in the workplace reduce strain and injury.",
        "Vaccination helps prevent the spread of infectious diseases.",
        "Nutrition education is crucial for making healthy choices.",
        "Health education empowers individuals to take control of their well-being.",
        "Staying socially active contributes to mental and emotional health.",
        "Oral health is connected to overall health.",
        "Strong bones and joints are essential for mobility.",
        "Good hygiene habits start in childhood and continue throughout life.",
        "Preventing accidents and injuries is a priority for health and safety.",
        "Healthy aging involves staying active and engaged.",
    };

    vector<string> schoolSentences = {
        "Education is the key to success.",
        "Teachers play a crucial role in students' lives.",
        "Homework can be challenging but is essential for learning.",
        "School is a place for acquiring knowledge and skills.",
        "Reading is a fundamental skill for academic success.",
        "Mathematics teaches problem-solving and logic.",
        "Science classes inspire curiosity about the world.",
        "Art and music classes foster creativity.",
        "Physical education promotes a healthy lifestyle.",
        "History helps us understand the past and its impact on the present.",
        "Writing essays improves communication skills.",
        "Learning a foreign language opens doors to new cultures.",
        "School libraries are treasure troves of information.",
        "Standardized tests assess students' knowledge and abilities.",
        "Group projects teach collaboration and teamwork.",
        "Extracurricular activities provide opportunities for growth.",
        "School uniforms promote a sense of unity.",
        "Teachers inspire students to achieve their dreams.",
        "Classroom discussions encourage critical thinking.",
        "Students benefit from a well-structured curriculum.",
        "Grades reflect students' academic performance.",
        "Parent-teacher conferences facilitate communication.",
        "Student-teacher relationships are built on trust.",
        "Education is a lifelong journey.",
        "Digital technology enhances the learning experience.",
        "Online learning offers flexibility and accessibility.",
        "Science labs are hubs of experimentation and discovery.",
        "School buses ensure safe transportation.",
        "Field trips bring learning to life outside the classroom.",
        "College and career readiness is a primary goal of education.",
        "Scholarships make higher education affordable.",
        "The school library is a quiet place for reading and study.",
        "School assemblies promote school spirit.",
        "Pencils, notebooks, and textbooks are classroom essentials.",
        "The school bell marks the beginning and end of lessons.",
        "Report cards provide feedback on student progress.",
        "Classroom decorations create an inspiring learning environment.",
        "Exams challenge students to demonstrate their knowledge.",
        "Educational posters provide visual aids for learning.",
        "The school year is divided into semesters or quarters.",
        "The school cafeteria serves nutritious meals.",
        "Parent involvement strengthens the school community.",
        "Physical fitness is important for students' well-being.",
        "Educational games make learning fun.",
        "Inclusive education benefits students with diverse needs.",
        "Student council represents the student body's voice.",
        "Teachers invest in students' futures.",
        "High school graduation is a significant milestone.",
    };

    vector<string> politicsSentences = {
        "Political parties shape the government.",
        "Elections are a cornerstone of democracy.",
        "Leaders make important policy decisions.",
        "Public opinion influences political decisions.",
        "Campaigns are a crucial part of the electoral process.",
        "Legislation impacts citizens' lives.",
        "Laws are enacted by the legislative branch.",
        "The Constitution guides the political system.",
        "Judges interpret and apply the law.",
        "Citizens have the right to vote.",
        "Democracy allows for diverse political views.",
        "Freedom of speech is a fundamental right.",
        "Political debates are common during campaigns.",
        "Government officials serve their constituents.",
        "Taxation is a means to fund public services.",
        "Foreign policy affects international relations.",
        "The President leads the executive branch.",
        "Congress consists of the House and Senate.",
        "Senators represent states in the upper chamber.",
        "The House of Representatives is based on population.",
        "Lobbyists influence legislative decisions.",
        "Political ideologies vary widely.",
        "Partisanship can lead to gridlock.",
        "Bipartisanship is a cooperative approach.",
        "Checks and balances prevent abuses of power.",
        "Political polarization can divide the nation.",
        "The Supreme Court interprets the Constitution.",
        "The First Amendment protects free speech.",
        "Campaign finance reform seeks transparency.",
        "Civic engagement is essential for democracy.",
        "Government agencies enforce regulations.",
        "Cabinet members advise the President.",
        "The electoral college determines the President.",
        "Political primaries select party candidates.",
        "Political conventions nominate presidential candidates.",
        "The United Nations promotes international cooperation.",
        "The State Department handles foreign affairs.",
        "The Department of Defense manages the military.",
        "Voting is a civic duty and a right.",
        "Citizens can petition their government.",
        "Economic policies impact the nation's prosperity.",
        "The judicial branch upholds the rule of law.",
        "The legislative process involves debate and compromise.",
        "Politicians advocate for their constituents.",
        "Public opinion polls gauge popular sentiment.",
        "The media plays a vital role in informing the public.",
        "Government transparency fosters trust in democracy.",
        "The Bill of Rights protects individual liberties.",
        "Political science studies the government and politics.",
        "Civil rights movements have shaped U.S. history."
    };
    vector<string> travelSentences = {
        "Travel broadens the mind.",
        "Exploring new cultures is an enriching experience.",
        "Adventure awaits those who seek it.",
        "The world is full of breathtaking landscapes.",
        "Wanderlust is a powerful motivator.",
        "Visiting historic sites connects us to the past.",
        "Meeting new people is a highlight of travel.",
        "Trying local cuisine is a delicious adventure.",
        "Traveling exposes us to different traditions.",
        "Getting lost can lead to unexpected discoveries.",
        "The journey is often as rewarding as the destination.",
        "Trains offer a scenic way to travel.",
        "Cruises provide relaxation and exploration.",
        "Air travel allows us to cross continents quickly.",
        "Road trips are a classic American adventure.",
        "Backpacking is a budget-friendly way to see the world.",
        "Expeditions to remote places challenge our limits.",
        "Traveling solo builds independence and confidence.",
        "Traveling with friends creates lasting memories.",
        "Visiting natural wonders is awe-inspiring.",
        "Every destination has a unique story to tell.",
        "Camping under the stars is a humbling experience.",
        "Traveling by bicycle is eco-friendly and adventurous.",
        "Local markets offer a glimpse into daily life.",
        "Learning a few phrases in the local language goes a long way.",
        "Traveling to historical sites educates and inspires.",
        "Overcoming language barriers is part of the journey.",
        "Discovering hidden gems is a delightful surprise.",
        "Traveling by train is a relaxing way to see the countryside.",
        "Traveling by plane is fast but can be stressful.",
        "Exploring new cities offers endless possibilities.",
        "Hiking in the great outdoors rejuvenates the soul.",
        "Island destinations are a tropical paradise.",
        "Traveling by boat lets you set your own course.",
        "Traveling by car allows flexibility in your itinerary.",
        "Museums provide a deeper understanding of culture and history.",
        "Local guides share their passion and knowledge.",
        "Taking photos preserves memories for a lifetime.",
        "Traveling with an open heart fosters connections with locals.",
        "Documenting your travels in a journal is a cherished keepsake.",
        "Sampling street food is a culinary adventure.",
        "Respecting local customs shows cultural appreciation.",
        "Visiting UNESCO World Heritage Sites is a badge of honor.",
        "Traveling with family creates special bonding moments.",
        "Sunsets on the beach are a serene way to end the day.",
        "Admiring architectural marvels is a visual feast.",
        "Traveling can change your perspective on the world.",
        "The world is a book, and those who do not travel read only one page.",
        "Traveling is the only thing you can buy that makes you richer."
    };

    vector<string> popCultureSentences = {
        "Star Wars is a beloved science fiction franchise.",
        "The Beatles were one of the most iconic rock bands in history.",
        "Superheroes like Spider-Man and Batman are popular in comics and movies.",
        "Game of Thrones was a hit TV series with a complex story.",
        "The Harry Potter books captivated readers of all ages.",
        "Michael Jackson was the King of Pop and known for his moonwalk.",
        "Disney's animated movies have timeless classics like The Lion King.",
        "The Marvel Cinematic Universe brought many superheroes to the big screen.",
        "The Simpsons is a long-running animated TV show with memorable characters.",
        "Video games like Mario and Minecraft have huge fan bases.",
        "Hollywood is known for its glitzy red carpet events.",
        "Pokémon cards and games have been popular for decades.",
        "Social media platforms like Facebook and Instagram connect people worldwide.",
        "The Twilight series sparked a vampire craze in young adult literature.",
        "Star Trek has a dedicated fan base known as Trekkies.",
        "The Walking Dead is a TV series set in a zombie apocalypse.",
        "TikTok is a platform for short-form video content.",
        "The Lord of the Rings film trilogy is a fantasy epic.",
        "Elvis Presley is often called the King of Rock 'n' Roll.",
        "The Matrix is known for its iconic red pill or blue pill choice.",
        "Game shows like Jeopardy! and Wheel of Fortune are TV classics.",
        "Gaming consoles like PlayStation and Xbox are popular for gamers.",
        "The Mona Lisa is a famous painting by Leonardo da Vinci.",
        "The Beatles' album Sgt. Pepper's Lonely Hearts Club Band is legendary.",
        "Anime has a global following with diverse genres.",
        "Reality TV shows like Survivor and The Bachelor are entertaining.",
        "K-Pop music has a massive international fan base.",
        "Stephen King is a prolific author of horror and suspense novels.",
        "Comic-Con is a major event for fans of comics, movies, and TV shows.",
        "James Bond is known for his suave spy persona and gadgets.",
        "The Hunger Games books and movies depict a dystopian world.",
        "Hamilton is a hit musical that fuses hip-hop and history.",
        "The Mona Lisa is displayed in the Louvre Museum in Paris.",
        "Stranger Things is a popular series set in the 1980s with supernatural elements.",
        "The Simpsons has predicted real-life events in some episodes.",
        "The Kardashians are a famous reality TV family.",
        "Harry Potter's Hogwarts School of Witchcraft and Wizardry is a magical place.",
        "Comic book conventions like Comic-Con showcase cosplay and collectibles.",
        "Breaking Bad is a TV series about a chemistry teacher turned methamphetamine manufacturer.",
        "Anime conventions bring fans together to celebrate Japanese animation.",
        "The Beatles' Yellow Submarine is an animated musical adventure.",
        "Taylor Swift is known for her hit songs and storytelling lyrics.",
        "Jurassic Park was a groundbreaking film in terms of special effects.",
        "Spider-Man's web-swinging and wall-crawling abilities are iconic.",
        "The Simpsons' character Apu faced criticism for cultural representation.",
        "The Harry Potter films featured a young and talented cast.",
        "The Twilight series inspired a craze for vampire-themed novels and movies.",
        "The Oscars is a prestigious awards ceremony for the film industry."
    };

vector<string> gamingSentences = {
        "Gaming is a popular pastime for many people.",
        "Gamers enjoy playing a wide variety of video games.",
        "E-sports have gained recognition as competitive gaming events.",
        "Consoles like Xbox and PlayStation offer a great gaming experience.",
        "PC gamers prefer customizing their gaming setups.",
        "Mobile gaming has become a significant part of the industry.",
        "Game developers work hard to create engaging experiences.",
        "Multiplayer games allow players to compete or cooperate with others.",
        "The gaming community is diverse and welcoming.",
        "Achievements and trophies add a sense of accomplishment to games.",
        "Speedrunning is a challenging way to complete games quickly.",
        "Gamers often discuss strategies and tips in online forums.",
        "The video game industry generates billions of dollars in revenue.",
        "Retro gaming enthusiasts enjoy classic games from the past.",
        "Gaming conventions like E3 showcase upcoming titles.",
        "In-game microtransactions have become a controversial topic.",
        "Esports athletes practice and compete at a professional level.",
        "Game design involves creating engaging worlds and gameplay.",
        "Gaming can be a social activity with friends or online communities.",
        "Game addiction is a concern for some individuals.",
        "Game streaming platforms like Twitch provide live gameplay.",
        "Virtual reality gaming offers immersive experiences.",
        "Gaming consoles support both single-player and multiplayer modes.",
        "Mods and user-created content enhance gaming experiences.",
        "Online matchmaking connects players with similar skill levels.",
        "The world of gaming offers endless possibilities and adventures.",
        "Gamers appreciate well-crafted stories and characters in games.",
        "Gamification applies gaming concepts to non-gaming contexts.",
        "Competitive gaming requires teamwork and strategy.",
        "Game testing is an essential part of quality assurance.",
        "Board games and tabletop gaming are still enjoyed by many.",
        "Gamers collect in-game items and cosmetics.",
        "Gaming peripherals like mechanical keyboards enhance gameplay.",
        "Game development involves coding, art, and sound design.",
        "Gaming communities host events and tournaments.",
        "Gamers find comfort and excitement in virtual worlds.",
        "Esports organizations sponsor professional teams.",
        "The Steam platform offers a wide range of game titles.",
        "Indie game developers create unique and innovative experiences.",
        "Gaming events like PAX attract enthusiasts from around the world.",
        "Game music and soundtracks enhance the gaming experience.",
        "Gamers can customize their avatars and characters.",
        "Game reviews and ratings influence purchasing decisions.",
        "The rise of mobile gaming has led to casual gaming experiences.",
        "Gamers embrace the challenge of difficult games.",
        "Game art showcases stunning visual designs and aesthetics.",
        "Gamers appreciate the nostalgia of older titles.",
        "Game consoles have become multimedia entertainment centers.",
        "The gaming industry continually evolves and innovates.",
        "Gamers bond over shared gaming experiences."
    };

    vector<string> socialMediaSentences = {
        "Social media connects people from all over the world.",
        "Twitter allows users to post short messages called tweets.",
        "Instagram is a popular platform for sharing photos and videos.",
        "Facebook was founded by Mark Zuckerberg in 2004.",
        "LinkedIn is used for professional networking.",
        "TikTok is known for its short video content.",
        "YouTube is a platform for sharing and watching videos.",
        "Snapchat is known for its disappearing messages.",
        "Hashtags are commonly used to categorize content on social media.",
        "Social media influencers have a significant online presence.",
        "Online communities exist for various interests and hobbies.",
        "Many people use social media to stay updated on news and events.",
        "Privacy concerns are important when using social media.",
        "Social media algorithms determine what content users see.",
        "People often share personal achievements and milestones online.",
        "Brands and businesses use social media for marketing and promotion.",
        "Live streaming has become a popular feature on many platforms.",
        "Social media platforms have millions of active users.",
        "User-generated content is a significant part of social media.",
        "Friend requests and follows are common interactions on social media.",
        "Likes and reactions are used to show appreciation for posts.",
        "Social media can be a source of inspiration and creativity.",
        "Online friendships can lead to real-life connections.",
        "Blocking and reporting are tools to deal with online harassment.",
        "Social media has changed the way we communicate and share information.",
        "Social media addiction is a growing concern.",
        "The term 'viral' is often used to describe popular content.",
        "Advertising and sponsored posts are common on social media.",
        "FOMO (Fear of Missing Out) is a feeling associated with social media.",
        "Selfies are a common type of photo shared on social platforms.",
        "Social media platforms are available as mobile apps.",
        "Social media can be both a positive and negative influence on mental health.",
        "The use of emojis has become a language of its own on social media.",
        "Social media trends come and go quickly.",
        "User engagement is important for content creators and brands.",
        "Social media can be a platform for activism and social change.",
        "Online debates and discussions are common on social media.",
        "Social media provides a platform for self-expression and opinions.",
        "Online trolls and cyberbullying can harm users' experiences.",
        "The importance of fact-checking information on social media.",
        "Social media profiles often feature a profile picture and a cover photo.",
        "Content moderation is necessary to ensure safe online environments.",
        "Social media notifications can be distracting.",
        "The impact of social media on relationships and dating.",
        "User accounts can be verified to confirm authenticity.",
        "Privacy settings allow users to control who can see their content.",
        "Social media platforms use machine learning to recommend content.",
        "Social media is a tool for sharing experiences and memories.",
        "The role of social media in political campaigns and movements."
    };

    vector<string> futureSentences = {
        "The future is full of possibilities.",
        "Technological advancements will reshape our world.",
        "AI and automation will play a significant role in the future job market.",
        "Space exploration will continue to expand our understanding of the universe.",
        "The future of energy lies in renewable sources like solar and wind power.",
        "Climate change is a pressing issue for future generations to address.",
        "Medical breakthroughs will lead to longer and healthier lives.",
        "The internet will continue to connect people around the globe.",
        "Education will evolve to meet the demands of the future workforce.",
        "Quantum computing holds the potential to revolutionize information processing.",
        "In the future, humans may establish colonies on other planets.",
        "The development of smart cities will improve urban living.",
        "Sustainable practices are essential for a greener future.",
        "The future of transportation includes electric and autonomous vehicles.",
        "Genetic engineering will lead to personalized medicine.",
        "Artificial intelligence will assist in solving complex problems.",
        "Renewable energy will reduce our dependence on fossil fuels.",
        "The future workplace will be adaptable and flexible.",
        "Virtual reality will change the way we interact with technology.",
        "The future holds opportunities for space tourism.",
        "Advancements in robotics will impact various industries.",
        "The future of healthcare includes telemedicine and remote monitoring.",
        "Education will become more accessible through online learning.",
        "In the future, 3D printing will revolutionize manufacturing.",
        "Green technology will combat environmental challenges.",
        "Future generations will explore the depths of the oceans.",
        "The future of food production will involve vertical farming.",
        "Artificial intelligence will assist in creative endeavors.",
        "The future of entertainment will be immersive and interactive.",
        "Quantum mechanics will lead to secure communication networks.",
        "Renewable energy will lead to a cleaner and greener planet.",
        "The future workplace will emphasize remote collaboration.",
        "Space agencies will conduct missions to Mars and beyond.",
        "Genetic editing will transform medical treatments.",
        "AI will revolutionize the customer service industry.",
        "In the future, flying cars may become a reality.",
        "The future of privacy will be a major concern in the digital age.",
        "The advancement of nanotechnology will impact multiple fields.",
        "Renewable energy sources will reduce carbon emissions.",
        "The future of fashion will incorporate sustainability.",
        "Machine learning will enhance data analysis in various domains.",
        "Quantum computing will break encryption codes.",
        "The future holds potential for exploring exoplanets.",
        "Advancements in space technology will benefit Earth.",
        "3D printing will enable customized and on-demand products.",
        "Artificial intelligence will enhance personalized recommendations.",
        "The future of transportation will prioritize eco-friendly options.",
        "Digital currencies may become the norm in the future.",
        "The development of AI-driven virtual assistants will continue.",
        "The future will see breakthroughs in clean energy technology."
    };

    vector<string> artSentences = {
        "Painting is a form of visual art.",
        "Leonardo da Vinci created the Mona Lisa.",
        "Sculptures can be made from various materials.",
        "The Sistine Chapel ceiling was painted by Michelangelo.",
        "Artists often find inspiration in nature.",
        "Impressionism is known for its use of light and color.",
        "Abstract art can be open to interpretation.",
        "Picasso is famous for his cubist works.",
        "Vincent van Gogh's Starry Night is iconic.",
        "Photography is a unique art form.",
        "The Louvre Museum houses famous art pieces.",
        "Art can evoke strong emotions.",
        "Calligraphy is a beautiful form of writing.",
        "Public art can be found in many cities.",
        "The use of perspective enhances realism in art.",
        "Ceramics and pottery are ancient art forms.",
        "The brushstroke technique varies among artists.",
        "Frida Kahlo's self-portraits are well-known.",
        "Street art often conveys social messages.",
        "Art exhibitions showcase diverse talents.",
        "Glassblowing is a delicate art form.",
        "The color wheel is a fundamental concept in art.",
        "Digital art is gaining popularity.",
        "Abstract expressionism emphasizes emotional expression.",
        "Art restoration preserves historical works.",
        "Watercolor paintings have a unique transparency.",
        "Collage art involves combining various materials.",
        "The use of light and shadow creates depth in art.",
        "Public murals can transform urban spaces.",
        "Printmaking techniques include etching and lithography.",
        "Art can be a reflection of culture and society.",
        "Landscapes have been a popular art subject for centuries.",
        "Cubism distorts and deconstructs objects.",
        "Famous artists often have distinct styles.",
        "Glass mosaics decorate many religious buildings.",
        "Portraits capture the essence of a person.",
        "Op art creates optical illusions.",
        "Art therapy can promote healing and self-expression.",
        "Pop art celebrates popular culture.",
        "Stained glass windows adorn churches and cathedrals.",
        "Surrealism explores the subconscious mind.",
        "Abstract art encourages individual interpretation.",
        "Folk art reflects traditional customs and beliefs.",
        "Body art includes tattoos and body painting.",
        "Art history examines the evolution of artistic styles.",
        "Textile art uses fabric as a creative medium.",
        "Sculptors shape stone, wood, and metal.",
        "Art movements influence generations of artists.",
        "The use of color symbolism adds depth to art.",
    };

    vector<string> historicalSentences = {
        "The pyramids of Egypt are marvels of ancient engineering.",
        "Julius Caesar was assassinated in 44 BC.",
        "The Industrial Revolution transformed society and industry.",
        "The Renaissance marked a period of great cultural achievement.",
        "Joan of Arc played a crucial role in the Hundred Years' War.",
        "The Declaration of Independence was signed in 1776.",
        "The fall of the Roman Empire marked the end of antiquity.",
        "The Wright brothers achieved the first powered flight in 1903.",
        "Genghis Khan built one of the largest empires in history.",
        "The Black Death had a devastating impact on medieval Europe.",
        "The Great Wall of China is a UNESCO World Heritage site.",
        "The Magna Carta laid the foundation for modern law.",
        "Leonardo da Vinci painted the Mona Lisa and The Last Supper.",
        "The Battle of Gettysburg was a turning point in the American Civil War.",
        "Cleopatra was the last Pharaoh of Egypt.",
        "The French Revolution led to the rise of Napoleon Bonaparte.",
        "The Titanic sank on its maiden voyage in 1912.",
        "The American Revolution led to the formation of the United States.",
        "The Renaissance saw advancements in art, science, and literature.",
        "The Spanish Armada was defeated by the English in 1588.",
        "The ancient Greeks made significant contributions to philosophy.",
        "The Berlin Wall fell in 1989, leading to the reunification of Germany.",
        "The Russian Revolution of 1917 brought about the Soviet Union.",
        "The moon landing in 1969 was a historic achievement.",
        "The Sistine Chapel ceiling was painted by Michelangelo.",
        "The Treaty of Versailles ended World War I.",
        "The Lewis and Clark expedition explored the American West.",
        "The Silk Road facilitated trade between Europe and Asia.",
        "The Great Depression had a profound impact on the world economy.",
        "The Emancipation Proclamation abolished slavery in the United States.",
        "The Battle of Stalingrad was a crucial battle in World War II.",
        "The Code of Hammurabi is one of the earliest known legal codes.",
        "The Renaissance saw the works of Shakespeare and Dante Alighieri.",
        "The Cuban Missile Crisis brought the world to the brink of nuclear war.",
        "The discovery of King Tutankhamun's tomb was a major archaeological find.",
        "The Battle of Thermopylae was a key event in the Greco-Persian Wars.",
        "The Spanish Inquisition aimed to enforce religious orthodoxy.",
        "The fall of Constantinople marked the end of the Byzantine Empire.",
        "The Transcontinental Railroad connected the east and west coasts of the U.S.",
        "The Renaissance produced masterpieces in art, music, and literature.",
        "The Industrial Revolution brought about significant technological advances.",
        "The assassination of Archduke Franz Ferdinand triggered World War I.",
        "The Opium Wars resulted in the colonization of Hong Kong by the British.",
        "The founding of Rome is traditionally dated to 753 BC.",
        "The Mayflower Compact established self-governance in the New World.",
        "The Salem witch trials led to the execution of accused witches.",
        "The construction of the Panama Canal revolutionized global trade.",
    };

    vector<string> computerScienceSentences = {
        "Algorithms are the heart of computer science.",
        "Data structures are essential for efficient programming.",
        "Computer scientists solve complex problems.",
        "Object-oriented programming is a powerful paradigm.",
        "Java is a popular language for software development.",
        "C++ is known for its high performance and versatility.",
        "Python is widely used for scripting and web development.",
        "Artificial intelligence is revolutionizing technology.",
        "Machine learning algorithms can make predictions.",
        "Computer vision enables machines to see and understand images.",
        "Web development involves HTML, CSS, and JavaScript.",
        "Cybersecurity is crucial to protect data and systems.",
        "Big data analytics extracts insights from large datasets.",
        "Cloud computing provides scalable and flexible resources.",
        "Blockchain technology secures transactions and records.",
        "The Internet of Things connects everyday devices to the internet.",
        "Computer networks enable communication between devices.",
        "Software engineering follows best practices for quality code.",
        "Version control systems help manage code changes.",
        "Agile methodologies promote iterative development.",
        "Debugging is a common task for programmers.",
        "Functional programming emphasizes immutability and purity.",
        "Operating systems manage hardware and software resources.",
        "The Linux kernel is open source and highly configurable.",
        "Databases store and retrieve structured data efficiently.",
        "SQL is a language for managing relational databases.",
        "NoSQL databases provide flexibility for unstructured data.",
        "DevOps practices combine development and operations.",
        "Continuous integration automates code integration and testing.",
        "Containerization with Docker simplifies deployment.",
        "Web frameworks like Django and Ruby on Rails speed up development.",
        "Mobile app development targets iOS and Android platforms.",
        "Artificial neural networks mimic the human brain.",
        "Machine learning models can classify data.",
        "Deep learning models excel in complex tasks like image recognition.",
        "Natural language processing analyzes and generates human language.",
        "The software development life cycle involves planning and testing.",
        "Data mining discovers patterns in large datasets.",
        "User experience design focuses on user-friendly interfaces.",
        "Web security safeguards against cyberattacks.",
        "Open-source software encourages collaboration and innovation.",
        "Parallel computing leverages multiple processors for speed.",
        "Quantum computing explores new dimensions of computation.",
        "The Turing test assesses artificial intelligence's human-likeness.",
        "Computer science fosters problem-solving and critical thinking.",
        "Coding bootcamps offer intensive programming training.",
        "Hacker culture celebrates creativity and curiosity.",
    };

    vector<string> randomSentences = {
        "The quick brown fox jumps over the lazy dog.",
        "Cats and dogs make wonderful pets.",
        "The world is full of natural beauty.",
        "Learning is a lifelong journey.",
        "Music can soothe the soul.",
        "Books take us to new worlds.",
        "Cooking is a creative art.",
        "Technology is rapidly advancing.",
        "Kindness is a universal language.",
        "Exploring nature is a great adventure.",
        "Travel broadens the mind.",
        "Friendship is a treasure.",
        "Hard work leads to success.",
        "Laughter is the best medicine.",
        "Artistic expression comes in many forms.",
        "Education is the key to knowledge.",
        "Dreams can become reality with dedication.",
        "Innovation drives progress.",
        "Health is wealth.",
        "Every cloud has a silver lining.",
        "Family is a source of support and love.",
        "Perseverance leads to achievement.",
        "Time is a precious resource.",
        "Science uncovers the mysteries of the universe.",
        "Creativity knows no bounds.",
        "Respect for others is fundamental.",
        "Curiosity fuels discovery.",
        "Diversity makes the world colorful.",
        "Silence can be golden.",
        "Imagination is a powerful tool.",
        "Teamwork achieves great goals.",
        "The past shapes the future.",
        "Nature has a calming effect.",
        "Patience is a virtue.",
        "Learning from mistakes is important.",
        "Adventure awaits around every corner.",
        "Equality is a human right.",
        "Adaptability is essential in a changing world.",
        "Empathy connects us as human beings.",
        "Simplicity is the ultimate sophistication.",
        "The universe is full of wonders.",
        "Life is a journey, not a destination.",
        "Balance is the key to happiness.",
        "Positivity is contagious.",
        "Elegance is in the details.",
        "Friendship knows no distance.",
        "Change is the only constant.",
        "Ambition leads to achievement.",
        "Wisdom comes with age.",
        "Love is the most powerful force.",
        "Courage overcomes fear.",
        "Success is the result of hard work.",
        "Nature's beauty is all around us.",
        "Invention transforms the world.",
        "Happiness is a choice we make.",
        "The world is full of opportunities.",
        "Life is what you make it.",
        "Adventure begins at the end of your comfort zone.",
        "Knowledge is the key to understanding.",
        "A smile brightens any day.",
        "Dream big and aim high.",
        "Kindness is a language everyone understands.",
        "Imagination has no boundaries.",
        "Family is a gift that lasts forever.",
        "Resilience conquers adversity.",
        "Perseverance leads to triumph.",
        "Wisdom comes from experience.",
        "Laughter is the music of the soul.",
        "The world is your oyster.",
        "Freedom is a fundamental right.",
        "Friendship warms the heart.",
        "Learning never ends.",
        "Success is a journey, not a destination.",
        "The beauty of life is in the little things.",
        "Innovation drives progress.",
        "Diversity enriches our lives.",
        "Balance is the key to a harmonious life.",
        "Exploration expands our horizons.",
        "Adventure is calling your name.",
        "Patience is a virtue.",
        "Nature's wonders are boundless.",
        "Embrace change and grow.",
        "Love makes the world go 'round.",
        "Kindness is a simple act that makes a big difference.",
        "Creativity fuels the imagination.",
        "Empathy connects us all.",
        "Courage is the strength to overcome fear.",
        "Wisdom comes from learning.",
        "Invention shapes the future.",
        "The journey of a thousand miles begins with a single step.",
        "Laughter is the best medicine.",
        "Dreams are the seedlings of reality.",
        "Success is a state of mind.",
        "The world is full of beauty and wonder.",
    };






vector<vector<string>> sentences = {spaceSentences, natureSentences, techSentences, foodSentences, sportsSentences,
    healthSentences, schoolSentences, politicsSentences, travelSentences, popCultureSentences, gamingSentences,
    socialMediaSentences, futureSentences, artSentences, historicalSentences, computerScienceSentences, randomSentences };



